POSSESSIONS_INV_TITLE_TEXT = "Possessions";
POSSESSIONS_INV_HELP = "Help1";
POSSESSIONS_INV_HELP2 = "Help2";
POSSESSIONS_INV_HELP3 = "Name";
POSSESSIONS_INV_HELP4 = "Rarity";

POSSESSIONS_TEXT_SEARCH = "Search";
POSSESSIONS_TEXT_ALLCHARS = "All chars";
POSSESSIONS_TEXT_ALLLOCS = "All locs";
POSSESSIONS_TEXT_ALLSLOTS = "All slots";

POSSESSIONS_TEXT_PLAYER = "Wearing";
POSSESSIONS_TEXT_BANK = "Bank";
POSSESSIONS_TEXT_INVENTORY = "Inventory";
POSSESSIONS_TEXT_INBOX = "Inbox";
POSSESSIONS_TEXT_KEYRING = "Keyring"


